# Kickstart container config file - see https://gitub.com/infracamp/kickstart
# Run ./kickstart.sh to start a development-container for this project
version: 1
from: "ghcr.io/nfra-project/kickstart-flavor-php:8.1"
ports: "80:80;4000:4000;4100:4100"

packages: [php8.1-curl, php8.1-http, php8.1-raphf]

command:
  build:


  dev:
    - "killall webpack || echo 'No Proc'"
    - "D:kick jekyll"

  init-workspaces:
    - "mkdir -p workspaces"
    - "git -C ./workspaces/ clone  git@github.com:dermatthes/leu-web-components.git"
    - "npm install"

  update:
    - "npm update"
    - "webpack build"

  killall:
    - killall jekyll
